# IMAGE
FROM node:16.13.2-alpine

# REPERTOIRE DE TRAVAIL DANS LE CONTAINER
WORKDIR /app

#COPIER PACKAGE.JSON
COPY package*.json ./

# INSTALLER LES DEPENDANCES
RUN npm install

# COPIER LE RESTE DES FICHIERS
COPY . .

# EXPOSE LE PORT QUE NOTRE APPLICATION UTILISE
EXPOSE 3000

# DEMARRAGE DE L'APPLICATION
CMD ["node", "server.js"]
